/**
 * The client's contract with the host half.
 *
 * A Remote contribution is a list of method descriptors, and this plugin has
 * to write them by hand: the Gateway's strict definitions are generated by a
 * Typert compiler this deployment does not ship, so `remote.$mount` is given
 * descriptors and the HOST reflects the real contract back from the Service
 * method signatures (`resolveSrcDescriptor`).
 *
 * What that means concretely, and the two rules that follow:
 *
 * - The client's validation is a MARKER gate, not a schema gate.
 *   `requireStrictInputs` only asserts that every parameter's codec says
 *   `mode: 'strict'`; it never reads the codec again. The result codec is not
 *   checked at all, and a result with no `decode` crosses back verbatim. So
 *   the descriptors below must name each parameter's wire field correctly (the
 *   host matches arguments by wire name) and must NOT attach a `decode` they
 *   do not have — the payloads are plain JSON.
 *
 * - `wire` must equal the host method's parameter name, because the host's
 *   SRC descriptor derives its own parameters from the real signature
 *   (`methodParameterNames`) and looks the value up by that name. Renaming a
 *   parameter on one side only is a silent argument mismatch.
 *
 * @module dsh-codex-oauth/client/api
 */
import type { AttemptView, CodexStatus } from '../wire.ts'

/** The Remote namespace, which is the host Service key. */
export const NAMESPACE = 'codexAuth'

/** The package name this contribution is attributed to in diagnostics. */
const PACKAGE = 'dsh-codex-oauth'

/**
 * The schema factory a `strict` codec must carry.
 *
 * Never called on this path — a client invocation sends raw JSON and the HOST
 * derives the real contract reflectively — but the registry insists one exists.
 * Declared in the shape zod v4 also exposes (Standard Schema v1) so that a host
 * which ever did evaluate it would get a usable, honest answer.
 */
interface CodecSchema {
  readonly '~standard': {
    readonly version: 1
    readonly vendor: string
    readonly validate: (value: unknown) => { readonly value: unknown } | { readonly issues: readonly { readonly message: string }[] }
  }
}

/**
 * A codec for a PARAMETER.
 *
 * Two gates disagree about what `strict` means and both must be satisfied:
 * the gateway refuses any parameter codec that is not `mode: 'strict'`
 * (`requireStrictInputs` in `dsh-api-gateway/lib/client.js`), while the
 * reflection registry requires every strict codec to carry a non-empty
 * `typeSymbol` and a `create()` factory (`validateCodec` in
 * `dsh-typert-registry/lib/client.js`). Satisfying only the first is what made
 * the first version of this bundle fail to mount at all, with a `TypeError`
 * thrown from inside the registry.
 *
 * `typeSymbol` follows the generated convention — `<package>#<endpoint>:<field>`
 * — rather than inventing a global type name for a value this plugin only ever
 * passes through.
 */
interface StrictCodec {
  readonly mode: 'strict'
  readonly typeSymbol: string
  readonly create: () => CodecSchema
}

/**
 * A codec for a RESULT.
 *
 * Deliberately `src-json`: the registry exempts it from the strict-codec rules,
 * the gateway never inspects a result codec, and the client's invocation path
 * passes a result through verbatim unless it carries its own `decode`. That is
 * exactly this plugin's position — the payload is plain JSON whose shape the
 * host owns, and pretending to a schema here would be a claim this bundle
 * cannot check.
 */
interface SrcJsonCodec {
  readonly mode: 'src-json'
}

/** The only parameter type this plugin sends: a string the human typed or chose. */
const TEXT_SCHEMA: CodecSchema = Object.freeze({
  '~standard': Object.freeze({
    version: 1 as const,
    vendor: 'dsh-codex-oauth',
    validate: (value: unknown) => (typeof value === 'string'
      ? { value }
      : { issues: [{ message: 'expected a string' }] }),
  }),
})

/** One parameter of a Remote method, as the client declares it. */
interface ParameterDescriptor {
  readonly name: string
  readonly wire: string
  readonly source: 'json'
  readonly codec: StrictCodec
}

/** One Remote method, as the client declares it. */
interface MethodDescriptor {
  readonly id: string
  readonly service: string
  readonly namespace: string
  readonly method: string
  readonly invocation: { readonly kind: 'direct' }
  readonly parameters: readonly ParameterDescriptor[]
  readonly result: SrcJsonCodec
}

/** The parameter codec for one endpoint's field, named the generated way. */
function strictTextCodec(method: string, field: string): StrictCodec {
  return {
    mode: 'strict',
    typeSymbol: `${PACKAGE}#${NAMESPACE}/${method}:${field}`,
    create: () => TEXT_SCHEMA,
  }
}

/** The result codec every method here uses. See {@link SrcJsonCodec}. */
const SRC_JSON_RESULT: SrcJsonCodec = Object.freeze({ mode: 'src-json' })

/** The contribution `remote.$mount` accepts. */
export interface RemoteContribution {
  readonly package: string
  readonly descriptors: readonly MethodDescriptor[]
}

/**
 * Declare one unary method.
 * @param method - the host method name, and the endpoint's last segment.
 * @param parameters - its parameters, in signature order.
 * @returns the descriptor.
 */
function unary(method: string, parameters: readonly string[] = []): MethodDescriptor {
  return {
    id: `${PACKAGE}#${NAMESPACE}/${method}`,
    service: NAMESPACE,
    namespace: NAMESPACE,
    method,
    invocation: { kind: 'direct' },
    parameters: parameters.map((name) => ({
      name,
      wire: name,
      source: 'json',
      codec: strictTextCodec(method, name),
    })),
    result: SRC_JSON_RESULT,
  }
}

/** The five methods the host Service exports, in declaration order. */
export const CONTRIBUTION: RemoteContribution = Object.freeze({
  package: PACKAGE,
  descriptors: [
    unary('status'),
    unary('signIn'),
    // `value` is `answer`'s parameter name on the host. See the module note.
    unary('answer', ['value']),
    unary('cancel'),
    unary('signOut'),
  ],
})

/** The Remote namespace surface once mounted. */
export interface CodexApi {
  status(): Promise<RemoteResponse<CodexStatus>>
  signIn(): Promise<RemoteResponse<AttemptView>>
  answer(value: string): Promise<RemoteResponse<AttemptView>>
  cancel(): Promise<RemoteResponse<AttemptView>>
  signOut(): Promise<RemoteResponse<CodexStatus>>
}

/**
 * The envelope every Remote call answers with.
 *
 * Success carries the host's return value under `value`; failure carries a
 * serialized error. A call whose transport broke also lands here, as a
 * `gateway/internal` failure, so a caller only ever unwraps one shape.
 */
export type RemoteResponse<T> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly error: { readonly message?: unknown; readonly code?: unknown } }

/**
 * Unwrap a Remote answer, or throw the host's own message.
 * @param response - what a method of {@link CodexApi} returned.
 * @returns the host's value.
 * @throws {Error} carrying the host's message when the call failed.
 */
export function unwrap<T>(response: RemoteResponse<T>): T {
  if (response.ok) return response.value
  const message = response.error?.message
  throw new Error(typeof message === 'string' && message.length > 0 ? message : '与 Harness 主进程通信失败')
}
